# Generated by Django 3.2.13 on 2023-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timbangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=255)),
                ('Alamat', models.CharField(max_length=255)),
                ('TipeSampah', models.CharField(max_length=255)),
                ('HargaPerKilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JumlahKilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HargaKeseluruhan', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
